################################################################################
# QwenCode — Qwen Code daemon (qwen serve) with Web Shell UI
# Mirrors the OpenCode Web workload: locally-built image pushed to the external
# registry, persistent state/workspaces on a PVC, shared cluster browser via
# the cdp-forward sidecar.
################################################################################

locals {
  qwen_image_name = "${local.registry_host}/${var.opencode_registry_namespace}/qwen:${var.qwen_version}"
}

################################################################################
# Docker Image Build (push is manual — see opencode precedent)
################################################################################

resource "docker_image" "qwen" {
  count = var.enable_qwen ? 1 : 0

  name = local.qwen_image_name

  build {
    context    = path.module
    dockerfile = "scripts/qwen.Dockerfile"
    build_args = {
      QWEN_VERSION = var.qwen_version
    }
  }
}

################################################################################
# Namespace + PVC
################################################################################

resource "kubectl_manifest" "qwen_namespace" {
  count = var.enable_qwen ? 1 : 0

  depends_on = [module.oke, time_sleep.after_cluster]

  manifest = {
    apiVersion = "v1"
    kind       = "Namespace"
    metadata = {
      name = "qwen"
      labels = {
        managed-by = "terraform"
      }
    }
  }
}

resource "kubectl_manifest" "qwen_pvc" {
  count = var.enable_qwen ? 1 : 0

  depends_on = [kubectl_manifest.qwen_namespace]

  manifest = {
    apiVersion = "v1"
    kind       = "PersistentVolumeClaim"
    metadata = {
      name      = "qwen-data"
      namespace = "qwen"
      labels = {
        app        = "qwen"
        managed-by = "terraform"
      }
    }
    spec = {
      accessModes      = ["ReadWriteOnce"]
      storageClassName = "oci-bv"
      resources = {
        requests = {
          storage = var.qwen_storage_size
        }
      }
    }
  }
}

################################################################################
# Secrets
################################################################################

resource "random_password" "qwen_admin" {
  count   = var.enable_qwen ? 1 : 0
  length  = 32
  special = true

  lifecycle {
    prevent_destroy = true
  }
}

locals {
  qwen_admin_password = var.enable_qwen ? (var.qwen_admin_password != "" ? var.qwen_admin_password : random_password.qwen_admin[0].result) : null
}

# Bearer token required by qwen serve on every API request (non-loopback bind).
resource "kubectl_manifest" "qwen_auth_secret" {
  count = var.enable_qwen ? 1 : 0

  depends_on = [kubectl_manifest.qwen_namespace]

  manifest = {
    apiVersion = "v1"
    kind       = "Secret"
    metadata = {
      name      = "qwen-auth"
      namespace = "qwen"
    }
    type = "Opaque"
    stringData = {
      QWEN_SERVER_TOKEN = local.qwen_admin_password
    }
  }
}

# Ingress-level basic auth (the Web Shell static assets are pre-auth at the
# daemon level; this gate protects the whole origin like OpenCode Web does).
# htpasswd is generated by scripts/gen_qwen_htpasswd.sh (no extra provider)
# and written to the git-ignored src/.tmp/qwen_htpasswd file.
resource "kubectl_manifest" "qwen_basic_auth_secret" {
  count = var.enable_qwen ? 1 : 0

  depends_on = [kubectl_manifest.qwen_namespace]

  manifest = {
    apiVersion = "v1"
    kind       = "Secret"
    metadata = {
      name      = "qwen-basic-auth"
      namespace = "qwen"
    }
    type = "Opaque"
    stringData = {
      auth = trimspace(file("${path.module}/.tmp/qwen_htpasswd"))
    }
  }
}

resource "kubectl_manifest" "qwen_llm_keys_secret" {
  count = var.enable_qwen ? 1 : 0

  depends_on = [kubectl_manifest.qwen_namespace]

  manifest = {
    apiVersion = "v1"
    kind       = "Secret"
    metadata = {
      name      = "qwen-llm-keys"
      namespace = "qwen"
    }
    type = "Opaque"
    stringData = merge(
      var.anthropic_api_key != "" ? { ANTHROPIC_API_KEY = var.anthropic_api_key } : {},
      var.openai_api_key != "" ? { OPENAI_API_KEY = var.openai_api_key } : {},
      var.openrouter_api_key != "" ? { OPENROUTER_API_KEY = var.openrouter_api_key } : {},
      var.ollama_cloud_api_key != "" ? { OLLAMA_CLOUD_API_KEY = var.ollama_cloud_api_key } : {},
      var.deepinfra_api_key != "" ? { DEEPINFRA_API_KEY = var.deepinfra_api_key } : {},
      var.alibaba_token_plan_api_key != "" ? { ALIBABA_TOKEN_PLAN_API_KEY = var.alibaba_token_plan_api_key } : {},
    )
  }
}

resource "kubectl_manifest" "qwen_dev_credentials" {
  count = var.enable_qwen ? 1 : 0

  depends_on = [kubectl_manifest.qwen_namespace]

  manifest = {
    apiVersion = "v1"
    kind       = "Secret"
    metadata = {
      name      = "qwen-dev-credentials"
      namespace = "qwen"
    }
    type = "Opaque"
    stringData = merge(
      var.github_token != "" ? { GITHUB_TOKEN = var.github_token } : {},
      var.gcp_service_account_key != "" ? { GOOGLE_APPLICATION_CREDENTIALS_JSON = var.gcp_service_account_key } : {},
      var.firebase_token != "" ? { FIREBASE_TOKEN = var.firebase_token } : {},
    )
  }
}

resource "kubectl_manifest" "qwen_tool_keys" {
  count = var.enable_qwen ? 1 : 0

  depends_on = [kubectl_manifest.qwen_namespace]

  manifest = {
    apiVersion = "v1"
    kind       = "Secret"
    metadata = {
      name      = "qwen-tool-keys"
      namespace = "qwen"
    }
    type = "Opaque"
    stringData = merge(
      var.gitlab_token != "" ? { GITLAB_TOKEN = var.gitlab_token } : {},
      var.gitlab_preview_token != "" ? { GITLAB_PREVIEW_TOKEN = var.gitlab_preview_token } : {},
      var.neon_api_key != "" ? { NEON_API_KEY = var.neon_api_key } : {},
      var.neon_org_id != "" ? { NEON_ORG_ID = var.neon_org_id } : {},
      var.expo_token != "" ? { EXPO_TOKEN = var.expo_token } : {},
      var.paddle_sandbox_api_key != "" ? { PADDLE_SANDBOX_API_KEY = var.paddle_sandbox_api_key } : {},
    )
  }
}

################################################################################
# Deployment
################################################################################

resource "kubectl_manifest" "qwen_deployment" {
  count = var.enable_qwen ? 1 : 0

  depends_on = [
    docker_image.qwen,
    kubectl_manifest.qwen_auth_secret,
    kubectl_manifest.qwen_llm_keys_secret,
    kubectl_manifest.qwen_dev_credentials,
    kubectl_manifest.qwen_tool_keys,
    kubectl_manifest.qwen_pvc,
  ]

  manifest = {
    apiVersion = "apps/v1"
    kind       = "Deployment"
    metadata = {
      name      = "qwen"
      namespace = "qwen"
      labels = {
        app        = "qwen"
        managed-by = "terraform"
      }
    }
    spec = {
      replicas = 1
      selector = {
        matchLabels = {
          app = "qwen"
        }
      }
      template = {
        metadata = {
          labels = {
            app = "qwen"
          }
        }
        spec = {
          securityContext = {
            fsGroup = 1000
          }
          initContainers = concat([
            {
              # qwen-code 0.23 refuses to boot the Conversations runtime
              # unless the state base dir is owned by the daemon uid and the
              # managed scratch root is owner-only. Legacy PVC state predates
              # both checks (root-owned dir, fsGroup setgid modes), so repair
              # it as root before the daemon starts.
              name    = "volume-ownership"
              image   = docker_image.qwen[count.index].name
              command = ["sh", "-c"]
              args = [
                <<-EOT
                set -e
                chown -R qwen:ubuntu /home/qwen/.qwen
                if [ -d /home/qwen/.qwen/scratch-workspaces ]; then
                  chmod 700 /home/qwen/.qwen/scratch-workspaces
                fi
                EOT
              ]
              securityContext = {
                runAsUser = 0
              }
              volumeMounts = [
                {
                  name      = "qwen-data"
                  mountPath = "/home/qwen/.qwen"
                  subPath   = "state"
                }
              ]
              resources = {
                requests = {
                  cpu    = "10m"
                  memory = "32Mi"
                }
                limits = {
                  cpu    = "200m"
                  memory = "128Mi"
                }
              }
            }
            ], var.enable_qwen_browser ? [
            {
              # Playwright client library on the PVC (the browsers live in the
              # shared paperclip-browser service; the client connects over CDP).
              name    = "browser-setup"
              image   = docker_image.qwen[count.index].name
              command = ["sh", "-c"]
              args = [
                <<-EOT
                set -e
                if [ "$(cat /home/qwen/.playwright/.version 2>/dev/null)" = "${var.paperclip_browser_version}" ]; then
                  echo "playwright ${var.paperclip_browser_version} already installed"
                  exit 0
                fi
                npm install --prefix /home/qwen/.playwright playwright@${var.paperclip_browser_version}
                echo "${var.paperclip_browser_version}" > /home/qwen/.playwright/.version
                EOT
              ]
              volumeMounts = [
                {
                  name      = "qwen-data"
                  mountPath = "/home/qwen/.playwright"
                  subPath   = "playwright"
                }
              ]
              resources = {
                requests = {
                  cpu    = "50m"
                  memory = "128Mi"
                }
                limits = {
                  cpu    = "500m"
                  memory = "512Mi"
                }
              }
            }
            ] : [], [
            {
              # Seeds base settings.json + QWEN.md into the state volume on
              # first boot; later edits made at runtime are preserved.
              name    = "qwen-config"
              image   = docker_image.qwen[count.index].name
              command = ["sh", "-c"]
              args = [
                <<-EOT
                set -e
                [ -f /home/qwen/.qwen/settings.json ] || cp /usr/local/share/qwen-settings.json /home/qwen/.qwen/settings.json
                [ -f /home/qwen/.qwen/QWEN.md ] || cp /usr/local/share/qwen-QWEN.md /home/qwen/.qwen/QWEN.md
                mkdir -p /home/qwen/projects/sandbox
                EOT
              ]
              volumeMounts = [
                {
                  name      = "qwen-data"
                  mountPath = "/home/qwen/.qwen"
                  subPath   = "state"
                },
                {
                  name      = "qwen-data"
                  mountPath = "/home/qwen/projects"
                  subPath   = "workspaces"
                }
              ]
              resources = {
                requests = {
                  cpu    = "10m"
                  memory = "32Mi"
                }
                limits = {
                  cpu    = "100m"
                  memory = "128Mi"
                }
              }
            }
          ])
          containers = concat([
            {
              name            = "qwen"
              image           = docker_image.qwen[count.index].name
              imagePullPolicy = "Always"
              args = [
                "serve",
                "--hostname", "0.0.0.0",
                "--port", "4170",
                "--workspace", "/home/qwen/projects/sandbox",
                # The Web Shell terminal posts to /session/:id/shell, which
                # stays disabled unless opted in (token auth is already
                # mandatory on this non-loopback bind).
                "--enable-session-shell",
              ]
              ports = [
                {
                  containerPort = 4170
                  name          = "http"
                }
              ]
              env = concat(
                [
                  {
                    name = "QWEN_SERVER_TOKEN"
                    valueFrom = {
                      secretKeyRef = {
                        name = "qwen-auth"
                        key  = "QWEN_SERVER_TOKEN"
                      }
                    }
                  },
                  {
                    # Headless container: never try to open a browser.
                    name  = "BROWSER"
                    value = "none"
                  },
                  {
                    # Keep memories isolated when sibling repository
                    # directories are registered as separate workspaces.
                    name  = "QWEN_CODE_MEMORY_PROJECT_SCOPE"
                    value = "workspace"
                  },
                  {
                    # Browser automation via the shared paperclip-browser
                    # service; the cdp-forward sidecar exposes it at
                    # localhost:9222 for tools that assume a local Chrome.
                    name  = "QWEN_BROWSER_CDP"
                    value = "http://localhost:9222"
                  },
                  {
                    # Playwright client installed on the PVC by browser-setup.
                    name  = "NODE_PATH"
                    value = "/home/qwen/.playwright/node_modules"
                  },
                  {
                    name  = "PATH"
                    value = "/home/qwen/.playwright/node_modules/.bin:/opt/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
                  }
                ],
                [for k in ["ANTHROPIC_API_KEY", "OPENAI_API_KEY", "OPENROUTER_API_KEY", "OLLAMA_CLOUD_API_KEY", "DEEPINFRA_API_KEY", "ALIBABA_TOKEN_PLAN_API_KEY"] : {
                  name = k
                  valueFrom = {
                    secretKeyRef = {
                      name     = "qwen-llm-keys"
                      key      = k
                      optional = true
                    }
                  }
                }],
                [for k in ["GITHUB_TOKEN", "GOOGLE_APPLICATION_CREDENTIALS_JSON", "FIREBASE_TOKEN"] : {
                  name = k
                  valueFrom = {
                    secretKeyRef = {
                      name     = "qwen-dev-credentials"
                      key      = k
                      optional = true
                    }
                  }
                }],
                [for k in ["GITLAB_TOKEN", "GITLAB_PREVIEW_TOKEN", "NEON_API_KEY", "NEON_ORG_ID", "EXPO_TOKEN", "PADDLE_SANDBOX_API_KEY"] : {
                  name = k
                  valueFrom = {
                    secretKeyRef = {
                      name     = "qwen-tool-keys"
                      key      = k
                      optional = true
                    }
                  }
                }]
              )
              resources = {
                requests = {
                  cpu    = "500m"
                  memory = "1Gi"
                }
                limits = {
                  cpu    = var.qwen_cpu_limit
                  memory = var.qwen_memory_limit
                }
              }
              livenessProbe = {
                tcpSocket = {
                  port = 4170
                }
                initialDelaySeconds = 30
                periodSeconds       = 10
              }
              readinessProbe = {
                tcpSocket = {
                  port = 4170
                }
                initialDelaySeconds = 10
                periodSeconds       = 5
              }
              volumeMounts = [
                {
                  name      = "qwen-data"
                  mountPath = "/home/qwen/.qwen"
                  subPath   = "state"
                },
                {
                  # The PVC root contains sibling repository workspaces. The
                  # empty sandbox is the fallback when a client omits cwd.
                  name      = "qwen-data"
                  mountPath = "/home/qwen/projects"
                  subPath   = "workspaces"
                },
                {
                  name      = "qwen-data"
                  mountPath = "/home/qwen/.playwright"
                  subPath   = "playwright"
                }
              ]
            }
            ], var.enable_qwen_browser ? [
            {
              # Shares the pod netns: tools inside the main container that
              # expect a LOCAL Chrome CDP endpoint find it at 127.0.0.1:9222,
              # forwarded to the shared paperclip-browser service.
              name    = "cdp-forward"
              image   = docker_image.qwen[count.index].name
              command = ["node", "-e", file("${path.module}/scripts/cdp_proxy.js")]
              env = [
                {
                  name  = "CDP_TARGET_HOST"
                  value = "paperclip-browser.paperclip.svc.cluster.local"
                },
                {
                  name  = "CDP_TARGET_PORT"
                  value = "9222"
                },
                {
                  name  = "CDP_LISTEN_PORT"
                  value = "9222"
                }
              ]
              resources = {
                requests = {
                  cpu    = "10m"
                  memory = "32Mi"
                }
                limits = {
                  cpu    = "200m"
                  memory = "128Mi"
                }
              }
            }
          ] : [])
          volumes = [
            {
              name = "qwen-data"
              persistentVolumeClaim = {
                claimName = "qwen-data"
              }
            }
          ]
          affinity = {
            podAntiAffinity = {
              preferredDuringSchedulingIgnoredDuringExecution = [
                {
                  weight = 100
                  podAffinityTerm = {
                    labelSelector = {
                      matchExpressions = [
                        {
                          key      = "app"
                          operator = "In"
                          values   = ["paperclip", "paperclip-db"]
                        }
                      ]
                    }
                    topologyKey = "kubernetes.io/hostname"
                  }
                }
              ]
            }
          }
        }
      }
    }
  }
}

################################################################################
# Service + Ingress
################################################################################

# Authentication and Origin-rewriting proxy in front of Qwen. Keeping this at
# the service boundary makes the protection independent of ingress-specific
# middleware: Basic credentials are validated and translated to the daemon
# token, while Bearer credentials pass through for daemon validation.
resource "kubectl_manifest" "qwen_auth_deployment" {
  count = var.enable_qwen ? 1 : 0

  depends_on = [kubectl_manifest.qwen_basic_auth_secret]

  manifest = {
    apiVersion = "apps/v1"
    kind       = "Deployment"
    metadata = {
      name      = "qwen-auth"
      namespace = "qwen"
      labels = {
        app        = "qwen-auth"
        managed-by = "terraform"
      }
    }
    spec = {
      replicas = 1
      selector = {
        matchLabels = {
          app = "qwen-auth"
        }
      }
      template = {
        metadata = {
          labels = {
            app = "qwen-auth"
          }
        }
        spec = {
          containers = [
            {
              name    = "gateway"
              image   = "docker.io/nginxinc/nginx-unprivileged:1.27-alpine"
              command = ["sh", "-c"]
              args = [
                <<-EOT
                cat > /etc/nginx/conf.d/default.conf <<'NGINX'
                map $http_authorization $qwen_auth_realm {
                  ~*^Bearer\s+ off;
                  default "QwenCode Web";
                }
                map $http_authorization $qwen_upstream_authorization {
                  ~*^Bearer\s+ $http_authorization;
                  default "Bearer __TOKEN__";
                }
                server {
                  listen 8081;
                  location / {
                    auth_basic $qwen_auth_realm;
                    auth_basic_user_file /etc/nginx/auth.htpasswd;
                    proxy_pass http://qwen.qwen.svc.cluster.local:80;
                    proxy_http_version 1.1;
                    proxy_set_header Authorization $qwen_upstream_authorization;
                    proxy_set_header Origin "http://127.0.0.1:4170";
                    proxy_set_header Host $host;
                    proxy_set_header Connection "";
                    proxy_buffering off;
                    proxy_read_timeout 3600s;
                    proxy_send_timeout 3600s;
                    client_max_body_size 50m;
                  }
                }
                NGINX
                sed -i "s|__TOKEN__|$QWEN_SERVER_TOKEN|" /etc/nginx/conf.d/default.conf
                exec nginx -g 'daemon off;'
                EOT
              ]
              env = [
                {
                  name = "QWEN_SERVER_TOKEN"
                  valueFrom = {
                    secretKeyRef = {
                      name = "qwen-auth"
                      key  = "QWEN_SERVER_TOKEN"
                    }
                  }
                }
              ]
              volumeMounts = [
                {
                  name      = "htpasswd"
                  mountPath = "/etc/nginx/auth.htpasswd"
                  subPath   = "auth"
                  readOnly  = true
                }
              ]
              resources = {
                requests = {
                  cpu    = "10m"
                  memory = "32Mi"
                }
                limits = {
                  cpu    = "300m"
                  memory = "256Mi"
                }
              }
            }
          ]
          volumes = [
            {
              name = "htpasswd"
              secret = {
                secretName = "qwen-basic-auth"
              }
            }
          ]
        }
      }
    }
  }
}

resource "kubectl_manifest" "qwen_auth_service" {
  count = var.enable_qwen ? 1 : 0

  depends_on = [kubectl_manifest.qwen_namespace]

  manifest = {
    apiVersion = "v1"
    kind       = "Service"
    metadata = {
      name      = "qwen-auth"
      namespace = "qwen"
    }
    spec = {
      type = local.qwen_public ? "NodePort" : "ClusterIP"
      ports = [
        {
          # Main entrypoint: the Origin-rewriting proxy in front of the daemon.
          port       = 80
          targetPort = 8081
          protocol   = "TCP"
          name       = "http"
        }
      ]
      selector = {
        app = "qwen-auth"
      }
    }
  }
}

resource "kubectl_manifest" "qwen_service" {
  count = var.enable_qwen ? 1 : 0

  depends_on = [kubectl_manifest.qwen_namespace]

  manifest = {
    apiVersion = "v1"
    kind       = "Service"
    metadata = {
      name      = "qwen"
      namespace = "qwen"
      labels = {
        app        = "qwen"
        managed-by = "terraform"
      }
    }
    spec = {
      type = "ClusterIP"
      ports = [
        {
          port       = 80
          targetPort = 4170
          protocol   = "TCP"
          name       = "http"
        }
      ]
      selector = {
        app = "qwen"
      }
    }
  }
}

resource "kubectl_manifest" "qwen_ingress" {
  count = local.qwen_public ? 1 : 0

  depends_on = [
    time_sleep.wait_for_ingress_lb,
    kubectl_manifest.qwen_service,
    kubectl_manifest.qwen_auth_service,
    kubectl_manifest.qwen_auth_deployment,
    kubectl_manifest.letsencrypt_issuer,
  ]

  manifest = {
    apiVersion = "networking.k8s.io/v1"
    kind       = "Ingress"
    metadata = {
      name      = "qwen"
      namespace = "qwen"
      annotations = merge(
        {
          "oci-native-ingress.oraclecloud.com/backend-tls-enabled" = "false"
        },
        local.qwen_tls ? merge({
          "oci-native-ingress.oraclecloud.com/https-listener-port" = "443"
          }, local.shared_listener_tls ? {
          "oci-native-ingress.oraclecloud.com/certificate-ocid" = var.oci_native_shared_certificate_ocid
          } : {
          "cert-manager.io/cluster-issuer" = "letsencrypt-prod"
          }) : {
          "oci-native-ingress.oraclecloud.com/http-listener-port" = "80"
        }
      )
    }
    spec = merge(
      local.qwen_tls && !local.shared_listener_tls ? {
        tls = [
          {
            hosts      = [var.qwen_custom_domain]
            secretName = "qwen-tls"
          }
        ]
      } : {},
      {
        ingressClassName = local.ingress_class
        rules = [
          {
            host = var.qwen_custom_domain
            http = {
              paths = [
                {
                  path     = "/"
                  pathType = "Prefix"
                  backend = {
                    service = {
                      name = "qwen-auth"
                      port = {
                        number = 80
                      }
                    }
                  }
                }
              ]
            }
          }
        ]
      }
    )
  }
}
